services:
  plaid-flash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plaid-flash
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    labels:
      com.plaid-flash.description: "Plaid Flash - Test Plaid Link, in a Flash"
